version: '2'
services:
    web:
        build:
            context: ./docker-images
            dockerfile: Dockerfile-php
        volumes:
            - ./:/var/www/html
        ports:
            - 8080:80
        depends_on:
            - db
    db:
        image: mariadb:5.5
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
